spring.application.name=car-dealer-springbatch
spring.output.ansi.enabled=ALWAYS

spring.datasource.url=jdbc:h2:mem:cardealer
spring.datasource.username=sa
spring.datasource.password=

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema-all.sql
spring.sql.init.data-locations=classpath:data.sql

app.filial-report-pattern=file:src/main/resources/filial-report/*.csv
app.matriz-report-file=src/main/resources/matriz-report/sales-report.csv